Add values to .Values.coordinator.deployment and .Values.worker.deplo…
trinodb/charts pull request #244
Opened 2024-10-07 17:35 UTC by amarthey

Reference PR: #236 

Adding deployment spec values for `coordinator` deployment and `worker` deployment:
```
 - progressDeadlineSeconds
 - revisionHistoryLimit
 - strategy
```
This is needed for us in case of an update of Trino Cluster that requires the deployment to bring pods up and down.

2024-10-07 18:20 UTC, amarthey commented
Sorry @nineinchnick , I re-opened a PR because I messed up the rebase and squash from #236 .

2024-10-08 15:15 UTC, amarthey commented on charts/trino/values.yaml
> +    # coordinator.deployment.progressDeadlineSeconds -- The maximum time in seconds for a deployment to make progress before it
good catch

2024-10-08 15:46 UTC, nineinchnick approved these changes
Almost good, please improve the commit message. See https://cbea.ms/git-commit/

2024-10-08 18:13 UTC, amarthey commented
@nineinchnicklLet me know if the commit message is correct.
I looked in the previous merged PRs and saw that usually commit message and PR title were matching.

2024-10-08 18:17 UTC, mosabua commented
"more deployment properties" is to vague

You can have a short title and then a paragraph with more info if desired. But is should not be vague. See more info at https://trino.io/development/process#pull-request-and-commit-guidelines-

2024-10-08 18:18 UTC, mosabua commented on charts/trino/values.yaml
> +    # is considered to be failed. The deployment controller will continue to
```suggestion
    # is considered to be failed. The deployment controller continues to
```

2024-10-08 18:18 UTC, mosabua commented on charts/trino/values.yaml
> +    # reason will be surfaced in the deployment status.
```suggestion
    # reason is surfaced in the deployment status.
```

2024-10-08 18:34 UTC, mosabua requested changes

2024-10-08 18:34 UTC, mosabua commented on charts/trino/values.yaml
> +    # is considered to be failed. The deployment controller will continue to
```suggestion
    # is considered to be failed. The deployment controller continues to
```

2024-10-08 18:34 UTC, mosabua commented on charts/trino/values.yaml
> +    # reason will be surfaced in the deployment status.
```suggestion
    # reason is surfaced in the deployment status.
```

2024-10-08 21:55 UTC, mosabua approved these changes
Lgtm now. Thanks!

2024-10-09 08:16 UTC, nineinchnick approved these changes

2024-10-09 08:16 UTC, merged