Seperate pod assignment config for worker & coordinator
trinodb/charts pull request #50
Opened 2022-06-27 19:38 UTC by oasisvali

This PR updates the `affinity`, `nodeSelector` and `tolerations` values to contain 2 sub-configurations, one for the worker and one for the coordinator. This allows seperate `affinity`, `nodeSelector` and `tolerations` configuration for the workers vs the coordinator pods. This is a common requirement as the resource requirements for a worker pod is usually different compared to a coordinator pod.

This PR enables this change in a non-backward-compatible way. If backward compatibility is required, I can update the PR so that the current format of `affinity`, `nodeSelector` and `tolerations` values are used as a common fallback for worker and coordinator pods.

2022-07-18 05:22 UTC, oasisvali commented
@hashhar any feedback on whether this PR should be updated to be backward-compatible and use the current format of affinity, nodeSelector and tolerations values as a common fallback for both worker and coordinator pods?

2022-07-18 10:28 UTC, hashhar commented
I think preserving backward compatibility is generally a good idea but I don't want it to prevent us from doing the right thing.

I'm fine with current approach you have. cc: @przemekak @radek-starburst 

I'll just take care to do a separate release which includes only this change so that people can easily upgrade to get other features and then wait to upgrade further to this version.

2022-07-18 10:30 UTC, hashhar requested changes
LGTM but let's wait for 0.9.0 with other changes.

2022-07-18 10:30 UTC, hashhar commented on charts/trino/Chart.yaml
> +version: 0.9.0
reminder to self: release 0.9.0 with other pending PRs and unreleased changes and then update this to 0.10.0.

2024-05-22 08:01 UTC, nineinchnick commented
I'll close this, since there was no activity here for a long time. Feel free to reopen after rebasing.

2024-05-22 08:01 UTC, closed without merging